version: "3.1"

services:
  nginx:
    build:
      context: ./requirements/nginx
    init: true
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # - wordpress:/var/www/html
      - ./data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - mynet

  wordpress:
    build:
      context: ./requirements/wordpress
    init: true
    container_name: wordpress
    restart: always
    volumes:
      # - wordpress:/var/www/html
      - ./data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynet

  db:
    build:
      context: ./requirements/mariadb
    init: true
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mariadb/:/var/lib/mysql
    networks:
      - mynet

volumes:
  wordpress:
#   mariadb:

networks:
  mynet:
    driver: bridge
